### ISSUE TITLE
Blockstack Browser does not work on ChromeOS

### ISSUE THREAD

**Issue by dantrevino** [blockstack/blockstack-browser#1269]
- Operating system and version
ChromeOS (Chrome 65)

- Blockstack version
Tested with the version at `browser.blockstack.org` and `https://deploy-preview-1256--reporter-beaver-73821.netlify.com/` on April 4.
- How you installed Blockstack
Browser install via https://deploy-preview-1256--reporter-beaver-73821.netlify.com/
- Steps to reproduce
1. Create an identity at any blockstack web based install
2. Sign into any app

- Screenshots or videos
![image](https://user-images.githubusercontent.com/7738/38348245-862f8ca0-3855-11e8-97bf-e148cf608721.png)

- Logs
![image](https://user-images.githubusercontent.com/7738/38348277-b3b004ac-3855-11e8-84f7-26cb45d9ba6f.png)

Related MDN article: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler

**Comment by brandonparee** [comment]
Looks like there is a custom library that Blockstack.js uses to handle the custom protocol (I think it is `blockstack://`). Here is a link to the library -- https://github.com/larrysalibra/custom-protocol-detection

Seems like there just needs to be additional logic to handle ChromeOS.

**Comment by larrysalibra** [comment]
Thanks for the pull request to https://github.com/larrysalibra/custom-protocol-detection/pull/1 - I've pushed a new release 1.1.4 of the library to NPM and will make a pull request to update the browser with it.

**Comment by Masonavic** [comment]
I am experiencing this same issue on Chrome OS. I can use the browser fine https://browser.blockstack.org/ but when I click the "Sign in with Blockstack" button on any app I get the dialog box at the beginning of this thread. Chrome OS ver. 71.0.3578.94

**Comment by geiseri** [comment]
I see it on Version 71.0.3578.127 also.

**Comment by seb-langen** [comment]
Still have this Problem on **Chrome OS Version 85.0.4183.131**

**Comment by markmhx** [comment]
Thanks for these additional reports. I'm re-opening so that @timstackblock can attempt to recreate the bug on our end so we can fix.
