### ISSUE TITLE
Unsupported protocol handler - Opera Browser

### ISSUE THREAD

**Issue by jehunter5811** [blockstack/blockstack-browser#1689]
Blockstack cannot be used in the Opera browser. Tested both Windows and Mac. See screenshots.

I believe the solution for similar issues with Firefox was to force direct everyone to browser.blockstack.org. Can that same solution be applied with Opera?
<img width="1255" alt="screen shot 2018-09-26 at 9 40 30 am" src="https://user-images.githubusercontent.com/10519834/46087821-c0350c00-c170-11e8-8c4a-885544a5473b.png">
<img width="926" alt="screen shot 2018-09-26 at 9 41 37 am" src="https://user-images.githubusercontent.com/10519834/46087822-c0350c00-c170-11e8-9c1b-fa996b52c6ed.png">

**Comment by yknl** [comment]
There's a PR open in blockstack.js that should fix this issue: https://github.com/blockstack/blockstack.js/pull/524

**Comment by jehunter5811** [comment]
Thanks @yknl. Hard to tell which repo to search in for things. Didn't find an issue in the browser repo, so I thought maybe Opera had been skipped :)

**Comment by markmhx** [comment]
Recently another user on Twitter reported problems with using Opera to auth: https://twitter.com/Accretence/status/1081927878625951744

**Comment by markmhx** [comment]
@zone117x Has this issue's solution been completely reviewed and as such can be closed in anticipation of release?

**Comment by zone117x** [comment]
Yes - with the caveat that on Opera, this minor error prompt still shows up for users without the native app installed, however, the user only has to dismiss the popup and https auth redirect happens as intended.
